require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '15.1'
prepare_react_native_project!

target 'AEDEventCapture' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
  )
end
